"use client";
import {FormEvent,useMemo,useState} from "react";
import {Search,Flame,ChevronRight,RotateCcw,ExternalLink,Lightbulb,Building2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Badge} from "@/components/ui/badge";
import {Accordion,AccordionContent,AccordionItem,AccordionTrigger} from "@/components/ui/accordion";

type QA={id:number;category:string;sub:string;question:string;short:string;conditions:string[];steps:string[];grounds:string[];note:string;keywords:string[]};
const raw=[
[1,"설치기준","스프링클러","연면적 400㎡ 미만이라도 6층 이상이면 스프링클러설비를 설치해야 하나요?","원칙적으로 6층 이상인 특정소방대상물은 연면적이 400㎡ 미만이어도 모든 층에 스프링클러설비를 설치해야 합니다.","층수·용도|허가 당시 적용례|증축·용도변경 여부","건축물대장 확인|적용례 검토|설계도서 확인|관할 소방관서 확인","소방시설법 시행령 별표 4|법제처 18-0061|2022년 질의회신집 88쪽","건축허가 소방동의 대상 여부와 설치의무는 별도 판단입니다.","400|6층|스프링클러|연면적"],
[2,"설치기준","옥탑·부속공간","건축물의 층수와 면적에 포함되지 않는 옥탑에도 소방시설을 설치해야 하나요?","옥탑이 층수나 면적에 산입되지 않더라도 용도와 시설별 기준에 따라 감지기·유도등·스프링클러 헤드 등이 필요할 수 있습니다.","옥탑 구조·용도|출입·가연물 여부|시설별 설치기준","도면·사용상태 확인|요구시설 분류|NFPC·NFTC 적용|관할 소방관서 확인","소방시설법 제12조|시설별 화재안전기준|2022년 질의회신집 90쪽","모든 옥탑에 동일한 시설을 일률 적용할 수 없습니다.","옥탑|면적|층수|감지기|유도등"],
[3,"설치기준","내진설계","법적 의무 없이 자진 설치하는 스프링클러설비에도 내진설계를 적용해야 하나요?","건축행위와 무관한 자진설비는 법정 의무대상이 아닐 수 있으나 설치 경위를 확인해야 하며 내진기준에 맞춘 설치가 권장됩니다.","내진 대상물 여부|건축행위 동반 여부|자진·법정 설비 구분","인허가 이력 확인|시행령 제8조 확인|내진기준 검토|설계자·관할서 확인","소방시설법 제7조|시행령 제8조|소방시설의 내진설계 기준|2022년 질의회신집 94쪽","‘자진설비’라는 명칭만으로 제외를 확정하면 안 됩니다.","자진|내진|스프링클러"],
[4,"자체점검·유지관리","점검 연기","건물이 공실이거나 폐쇄된 경우 자체점검을 면제하거나 연기할 수 있나요?","공실·폐쇄만으로 자동 면제·연기되지 않습니다. 법정 사유에 해당하고 관할 소방본부장 또는 소방서장의 승인을 받아야 합니다.","법정 연기사유|실제 점검 곤란|증빙자료","사유·기간 정리|증빙과 신청서 제출|승인·점검시기 확인|승인 없이 기한 초과 금지","소방시설법 제22조제6항|시행령 제33조|시행규칙 별지 제7호|2022년 주요 Q&A 3쪽","2022년 공실·폐쇄 회신은 개별 사례입니다.","공실|폐쇄|점검|연기|면제"],
[5,"자체점검·유지관리","최초점검","증축으로 소방시설이 새로 설치된 경우 최초점검은 언제 해야 하나요?","최초점검 대상이라면 원칙적으로 건축물을 사용할 수 있게 된 날부터 60일 이내에 종합점검을 실시합니다.","새 시설 설치 여부|기존부 연계 여부|사용승인 대상 여부","기준일 확인|점검범위 결정|60일 내 종합점검|결과보고","소방시설법 제22조|시행규칙 별표 3|2022년 주요 Q&A 3쪽","현행 시행규칙의 기준일 표현을 우선합니다.","증축|최초점검|60일|사용승인"],
[6,"자체점검·유지관리","결과보고","자체점검에서 불량사항이 발견되면 이행계획서와 결과보고서를 어떤 순서로 제출하나요?","점검 결과와 이행계획서를 점검 종료일부터 15일 이내 보고하고, 조치 완료 후 증명자료와 함께 이행완료 보고를 해야 합니다.","불량사항 확인|중대위반 즉시 통보·조치|토요일·공휴일 미산입","결과 전달|이행계획 작성|15일 내 보고|기한 내 보수|완료일부터 10일 내 완료보고","소방시설법 제23조|시행규칙 제23조·별지 9·10·11호|2022년 주요 Q&A 4쪽","이행기한과 연기는 불량 종류와 법정 사유에 따라 달라집니다.","이행계획|결과보고|불량|15일|10일"],
[7,"행정처리","법령 적용","건축허가 접수 후 소방관계법령이 개정되면 어느 시점의 기준을 적용하나요?","접수일이나 공사일로 일률 판단하지 않고 개정 법령의 시행일과 부칙의 적용례·경과조치를 먼저 확인해야 합니다.","인허가 일자|부칙 기준행위|설계변경 여부","개정·시행일 확인|부칙 확인|인허가 이력 대조|경계시점 협의","각 개정 법령 부칙|예방소방업무처리규정|2022년 질의회신집 86쪽","2022년의 ‘접수 시점’을 모든 개정법령에 일반화하면 안 됩니다.","건축허가|개정|적용|접수|시행일"],
[8,"행정처리","착공신고","칸막이를 설치하면서 스프링클러 헤드를 추가하면 착공신고를 해야 하나요?","헤드 추가만으로 항상 신고대상은 아닙니다. 방호구역 증설이나 설비의 신설·증설·개설·이전·정비 여부를 확인해야 합니다.","방호구역 변경|계통 변경|신고대상 공사 여부","변경 도면 비교|공사 종류 검토|대상이면 사전 신고|도면으로 관할서 확인","소방시설공사업법 제13조|시행령 제4조|시행규칙 제12조|2022년 질의회신집 226쪽","2022년 사례는 특정 현장을 전제로 한 개별 회신입니다.","칸막이|헤드|착공|신고|방호구역"],
[9,"행정처리","완공검사","한 층의 일부 공사만 끝난 경우에도 부분완공검사를 신청할 수 있나요?","전체 준공 전 일부를 사용할 필요가 있고 그 부분의 소방시설공사가 완료됐다면 부분완공검사를 신청할 수 있습니다.","공사구역 안전 구분|소방시설 정상 작동|건축 부분사용승인 범위 일치","범위 특정|연계상태 확인|부분완공 신청|추가 안전조치 협의","소방시설공사업법 제14조제2항|부분완공검사 신청서식|2022년 질의회신집 229~230쪽","건축법상 부분사용승인도 함께 확인해야 합니다.","부분완공|일부|완공검사|층"],
[10,"현장 질의·예외","비화재보","비화재보를 확인한 뒤 수신기 경보를 일시 정지하고 복구하는 것은 법 위반인가요?","화재가 아님을 현장에서 확인하고 최소 시간 정지한 뒤 즉시 복구할 수 있지만, 확인 없이 정지하거나 방치하면 법 위반이 될 수 있습니다.","실제 화재 우선 확인|최소 범위·시간|안전조치 준수","현장 확인|관리 아래 일시 정지|원인 제거|즉시 복구·기록","소방시설법 제12조제3·4항|폐쇄·차단 행동요령 고시|2022년 질의회신집 89~92쪽","추정만으로 경보를 정지하면 안 됩니다.","비화재보|수신기|경보|정지|오동작"],
[11,"현장 질의·예외","피난시설","통행에 방해되지 않도록 공용복도에 자전거를 보관해도 되나요?","피난시설인 복도에 물건을 쌓는 행위는 원칙적으로 금지되므로 통행에 방해되지 않는다는 이유만으로 계속 보관해도 된다고 단정할 수 없습니다.","피난경로 여부|유효폭·이동 가능성|소방활동 장애","피난계획도 확인|장애 점검|가능성 있으면 제거|관리주체·관할서 확인","소방시설법 제16조|2022년 질의회신집 97~98쪽","포상금 제외기준과 적치행위의 적법성은 별개입니다.","자전거|복도|적치|피난|장애물"],
[12,"현장 질의·예외","임시소방시설","그라인더·금속 절단 작업도 임시소방시설을 설치해야 하는 화재위험작업인가요?","불꽃이나 고온 스파크가 발생한다면 화재위험작업에 해당할 수 있으므로 작업 전에 법정 임시소방시설을 설치해야 합니다.","공사현장 여부|불꽃·고열 발생|필요 시설 종류","위험평가·가연물 제거|별표 8 시설 설치|화기감독·감시|잔불 확인","소방시설법 제15조|시행령 제18조·별표 8|2022년 질의회신집 100~101쪽","작업명보다 실제 불꽃·열 발생 여부가 중요합니다.","그라인더|절단|임시소방시설|불꽃|화재위험"]
] as const;
const qas:QA[]=raw.map(r=>({id:r[0],category:r[1],sub:r[2],question:r[3],short:r[4],conditions:r[5].split("|"),steps:r[6].split("|"),grounds:r[7].split("|"),note:r[8],keywords:r[9].split("|")}));
const categories=["설치기준","자체점검·유지관리","행정처리","현장 질의·예외"],featured=[1,4,8,10];

export default function Home(){
 const [query,setQuery]=useState(""),[selected,setSelected]=useState<QA|null>(null),[category,setCategory]=useState<string|null>(null),[sub,setSub]=useState<string|null>(null);const [showAll,setShowAll]=useState(false),[noResult,setNoResult]=useState(false),[policy,setPolicy]=useState(false);
 const categoryQas=useMemo(()=>qas.filter(q=>q.category===category),[category]),subs=useMemo(()=>Array.from(new Set(categoryQas.map(q=>q.sub))),[categoryQas]);
 function choose(q:QA){setSelected(q);setQuery(q.question);setNoResult(false);setPolicy(false);setTimeout(()=>document.getElementById("answer")?.scrollIntoView({behavior:"smooth"}),0)}
 function submit(e:FormEvent){e.preventDefault();const x=query.trim().toLowerCase();if(!x)return;const found=qas.find(q=>q.question.toLowerCase().includes(x)||q.keywords.some(k=>x.includes(k.toLowerCase())));if(found)choose(found);else{setSelected(null);setNoResult(true)}}
 function reset(){setSelected(null);setQuery("");setCategory(null);setSub(null);setNoResult(false);setPolicy(false);window.scrollTo({top:0,behavior:"smooth"})}
 return <main><header className="topbar"><div className="shell header-inner"><div className="brand"><span className="mark" aria-label="소방청 마크 위치"><Flame size={20}/></span>소방업무 AI 챗봇</div><Badge variant="outline" className="prototype">서비스 제안용 시제품 · 공식 서비스 아님</Badge></div></header>
 <section className="hero"><div className="shell hero-grid"><div><p className="eyebrow">FIRE SERVICE · AI ASSISTANT</p><h1>복잡한 소방업무,<br/><span>근거와 절차로 명확하게.</span></h1><p>법령·지침·질의회신을 찾는 시간을 줄이고, 필요한 확인 순서를 한 흐름으로 안내합니다.</p></div><div className="system-graphic" aria-hidden="true"><div className="radar"><Flame size={38}/></div><span>법령</span><span>절차</span><span>근거</span></div></div></section>
 <section className="shell search-panel"><form onSubmit={submit} className="search-form"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="무엇이 궁금하신가요? 예: 공실 건물도 자체점검을 해야 하나요?" aria-label="소방업무 질문"/><Button type="submit">질문하기</Button></form><div className="quick-head"><strong>추천 질문</strong><Button variant="ghost" size="sm" onClick={()=>setShowAll(v=>!v)}>{showAll?"접기":"전체 12개 보기"}</Button></div><div className="quick-grid">{(showAll?qas:qas.filter(q=>featured.includes(q.id))).map(q=><button key={q.id} onClick={()=>choose(q)}><span>{q.category}</span>{q.question}<ChevronRight size={16}/></button>)}</div></section>
 <section className="shell browse"><div className="section-heading"><div><p className="eyebrow">분야별 찾기</p><h2>업무분야를 선택하세요</h2></div><Building2/></div><div className="category-grid">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>{setCategory(c);setSub(null)}}>{c}<ChevronRight size={18}/></button>)}</div>{category&&<div className="drilldown"><div className="sub-list">{subs.map(s=><button key={s} className={sub===s?"active":""} onClick={()=>setSub(s)}>{s}</button>)}</div>{sub&&<div className="question-list">{categoryQas.filter(q=>q.sub===sub).map(q=><button key={q.id} onClick={()=>choose(q)}>{q.question}<ChevronRight size={17}/></button>)}</div>}</div>}</section>
 {(selected||noResult)&&<section id="answer" className="answer-wrap"><div className="shell"><div className="user-bubble">{query}</div>{noResult?<div className="bot-bubble empty"><div className="bot-label"><Flame size={17}/> 소방업무 AI 챗봇</div><h2>현재 시제품에 등록되지 않은 질문입니다.</h2><p>공식 구축 시 소방청 법령·지침·질의회신 데이터베이스와 연계됩니다. 추천질문 또는 분야별 찾기를 이용해 주세요.</p></div>:selected&&<div className="bot-bubble"><div className="bot-label"><Flame size={17}/> 소방업무 AI 챗봇</div><div className="conclusion"><span>한 줄 결론</span><strong>{selected.short}</strong></div><div className="answer-columns"><div><h3>적용 조건</h3><ul>{selected.conditions.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>처리 절차</h3><ol>{selected.steps.map(x=><li key={x}>{x}</li>)}</ol></div></div><Accordion type="single" collapsible className="source-accordion"><AccordionItem value="source"><AccordionTrigger>관련 근거와 원문 확인</AccordionTrigger><AccordionContent><ul>{selected.grounds.map(x=><li key={x}>{x}</li>)}</ul><a href="https://www.law.go.kr" target="_blank" rel="noreferrer">국가법령정보센터 원문 확인 <ExternalLink size={14}/></a></AccordionContent></AccordionItem></Accordion><div className="note"><strong>추가 확인사항</strong><p>{selected.note}</p></div><div className="contact"><strong>담당부서 문의</strong><p>대상물 소재지 관할 소방관서 예방업무 담당부서에 도면과 인허가 이력을 제시해 확인하세요.</p></div><p className="demo-note">현재 답변은 기능 시연용입니다. 실제 적용 전 최신 법령과 대상물 현황을 확인하세요.</p><div className="answer-actions"><Button variant="outline" onClick={()=>setPolicy(v=>!v)}><Lightbulb size={16}/> 제도개선 의견으로 전환</Button><Button variant="ghost" onClick={reset}><RotateCcw size={16}/> 새 질문</Button></div>{policy&&<div className="policy"><h3>제도개선 의견서 초안</h3><p><strong>현황</strong> 법령과 회신자료가 분산되어 유사 질의가 반복됩니다.</p><p><strong>문제점</strong> 검색 경험에 따라 확인 시간과 답변 방식이 달라질 수 있습니다.</p><p><strong>개선방안</strong> 자연어 질문과 분야별 탐색을 공식자료에 연결하고 결론·조건·절차·근거를 구조화합니다.</p><p><strong>기대효과</strong> 자료 탐색시간 단축과 일관된 업무처리를 지원합니다.</p></div>}<div className="related"><h3>관련 질문</h3><div>{qas.filter(q=>q.category===selected.category&&q.id!==selected.id).slice(0,3).map(q=><button key={q.id} onClick={()=>choose(q)}>{q.question}</button>)}</div></div></div>}</div></section>}
 <footer><div className="shell"><strong>소방업무 AI 챗봇</strong><p>서비스 제안용 시제품 · 공식 서비스 아님 · 개인정보를 입력하지 마세요.</p></div></footer></main>}
